# -*- coding: utf-8 -*-
"""Image_Restoration_and_Colorization_using_DeOldify

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7OFtI1wOZCmVtCdWE9s1ar5_BbxMUV7

# **Image Restoration and Colorization using DeOldify**

This notebook demonstrates the restoration and colorization of black-and-white images using the DeOldify deep learning model. The system automatically generates realistic colorized versions of grayscale photographs and provides the output for download.

## Objective

The objective of this project is to:

- Restore visual appearance of grayscale photographs.
- Generate realistic colorized images using AI.
- Compare the original and colorized outputs.
- Provide downloadable colorized results.
"""

import os
import sys
import warnings
import collections
import collections.abc
import matplotlib.pyplot as plt

from PIL import Image
from google.colab import files

"""## Environment Setup

The required libraries, dependencies, and DeOldify model are installed and configured in this section.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# 
# !pip install torch==2.3.1 torchvision==0.18.1
# !pip install protobuf==3.20.3

!git clone -q https://github.com/mmaithani/DeOldify.git

sys.path.append("/content/DeOldify")

import torchvision.transforms.functional as F
sys.modules['torchvision.transforms.functional_tensor'] = F

if not hasattr(collections, "Iterable"):
    collections.Iterable = collections.abc.Iterable

if not hasattr(collections, "Sized"):
    collections.Sized = collections.abc.Sized

from deoldify import device
from deoldify.device_id import DeviceId

device.set(device=DeviceId.GPU0)

"""## DeOldify Model Initialization

The DeOldify artistic colorization model is loaded and prepared for image processing using GPU acceleration when available.
"""

!pip install -q -r /content/DeOldify/colab_requirements.txt

from deoldify.visualize import *
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

os.makedirs("/content/DeOldify/models", exist_ok=True);

!wget -q https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth \
-O /content/DeOldify/models/ColorizeArtistic_gen.pth

os.chdir('/content/DeOldify')
colorizer = get_image_colorizer(
    artistic=True
)
os.chdir('/content/')

"""## Image Upload

Upload a black-and-white or grayscale image for restoration and colorization.
"""

uploaded = files.upload()

img_path = next(iter(uploaded))

original = Image.open(img_path).convert("RGB")

plt.figure(figsize=(6,6))
plt.imshow(original)
plt.axis("off")
plt.show()

"""## Output Result Comparison

The original image and the colorized output are displayed side-by-side for visual comparison.
"""

os.chdir("/content/DeOldify")

os.makedirs("result_images", exist_ok=True)

output_path = colorizer.plot_transformed_image(
    path=f"/content/{img_path}",
    render_factor=45,
    compare=False,
    watermarked=False
)

colorized = Image.open(output_path).convert("RGB")

plt.figure(figsize=(16,8))

plt.subplot(1,2,1)
plt.imshow(original)
plt.title("Input")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(colorized)
plt.title("DeOldify Output")
plt.axis("off")

plt.tight_layout()
plt.show()

files.download(output_path)